# Generated by Django 3.1.4 on 2020-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_solved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
