# Generated by Django 3.1.4 on 2020-12-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='role_department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user_role',
        ),
        migrations.AddField(
            model_name='role',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.department'),
        ),
    ]
