# Generated by Django 3.1.4 on 2021-01-10 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0025_auto_20210108_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_user',
            field=models.ManyToManyField(related_name='project_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
