# Generated by Django 3.1.4 on 2021-01-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0026_auto_20210110_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_user',
        ),
        migrations.AddField(
            model_name='project',
            name='project_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
