# Generated by Django 3.1.4 on 2021-01-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_taskdiscussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdiscussion',
            old_name='project',
            new_name='task',
        ),
    ]
