# Generated by Django 3.1.4 on 2021-01-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20210111_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
