# Generated by Django 3.1.5 on 2021-01-16 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0032_devicecategory_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_user',
        ),
        migrations.AddField(
            model_name='project',
            name='project_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
